name: radio_mann
description: "Radio mann - A streaming radio application."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  
  # HTTP requests for API calls
  http: ^1.2.0
  
  # State management
  provider: ^6.1.5
  
  # Audio player for streaming
  just_audio: ^0.9.36
  
  # Image slider
  flutter_image_slideshow: ^0.1.6
  
  # Cached network image for efficient image loading
  cached_network_image: ^3.3.1
  
  # URL launcher for opening links, calls, etc.
  url_launcher: ^6.2.4
  
  # For handling SVG images
  flutter_svg: ^2.0.9
  
  # For photo gallery view
  photo_view: ^0.14.0
  
  # For video player
  video_player: ^2.8.2
  
  # For form validation
  form_field_validator: ^1.1.0
  
  # For showing toast messages
  fluttertoast: ^8.2.4
  
  # For handling permissions
  permission_handler: ^11.2.0
  
  # For loading animations
  loading_animation_widget: ^1.2.0+4
  
  # For date formatting
  intl: ^0.19.0
  
  # For additional icons including social media
  font_awesome_flutter: ^10.7.0
  change_app_package_name: ^1.5.0
  just_audio_background: ^0.0.1-beta.17
  audio_service: ^0.18.18
  audio_video_progress_bar: ^2.0.3
  marquee: ^2.3.0
  image_picker: ^1.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0



# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
