// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYtYxtjRJ-AwSV_tX-DlgKon0H6U0fk50',
    appId: '1:1013692787893:web:5ac881cb3bac2842a8e2fc',
    messagingSenderId: '1013692787893',
    projectId: 'radio-219c5',
    authDomain: 'radio-219c5.firebaseapp.com',
    storageBucket: 'radio-219c5.firebasestorage.app',
    measurementId: 'G-232X57GFHY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqBdUfQZKyWvzxZNBkSTtolvtwXvqCYbU',
    appId: '1:1013692787893:android:4d2f0f3119074d51a8e2fc',
    messagingSenderId: '1013692787893',
    projectId: 'radio-219c5',
    storageBucket: 'radio-219c5.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYtYxtjRJ-AwSV_tX-DlgKon0H6U0fk50',
    appId: '1:1013692787893:web:61fd1602e0824cc1a8e2fc',
    messagingSenderId: '1013692787893',
    projectId: 'radio-219c5',
    authDomain: 'radio-219c5.firebaseapp.com',
    storageBucket: 'radio-219c5.firebasestorage.app',
    measurementId: 'G-5951QK6SLM',
  );
}
